#!/usr/bin/env bash

set -e

LOCAL_BIN="${HOME}/.local/bin"

### ZSH ###
echo "switching default shell to zsh..."
sudo chsh --shell "$(which zsh)" "$(whoami)"

echo "install oh-my-zsh..."
sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

### RUSTBTW ###
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
rustup install nightly
cargo install --locked \
  atuin \
  bat \
  eza \
  ripgrep

if command -v apt-get &> /dev/null; then
  echo "installing apt packages..."

  # make sure we're always up to date on package sources
  sudo apt-get update

  sudo apt-get install -y \
    build-essential \
    cmake \
    curl \
    gettext \
    ninja-build \
    perl \
    tmux \
    unzip
fi


### FONTS ###
echo "installing fonts..."
FONTS_DIR=${HOME}/.local/share/fonts
if [[ uname == "Darwin" ]]; then
  FONTS_DIR=${HOME}/Library/Fonts
fi

wget https://github.com/ryanoasis/nerd-fonts/releases/download/v3.3.0/CascadiaCode.zip
unzip CascadiaCode.zip -d "$fonts_dir"
fc-cache -fv
rm -rf CascadiaCode.zip

echo "installing starship..."

### STARSHIP ###
# https://starship.rs/guide/#%F0%9F%9A%80-installation
# this script does updates as well, so it can always run
curl -fsSL https://starship.rs/install.sh | sh -s -- --bin-dir $LOCAL_BIN --yes

echo "installing neovim..."

### NEOVIM ###
# build nightly from source
git clone https://github.com/neovim/neovim
cd neovim && make CMAKE_BUILD_TYPE=RelWithDebInfo CMAKE_INSTALL_PREFIX=$LOCAL_BIN
make install
rm -rf neovim

echo "symlink dots..."

# Get the directory where the script is located
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

### SYMLINKS ###
ln -sf ${SCRIPT_DIR}/bash_aliases ${HOME}/.bash_aliases
ln -sf ${SCRIPT_DIR}/bashrc ${HOME}/.bashrc
ln -sf ${SCRIPT_DIR}/ghostty ${HOME}/.config/ghostty
ln -sf ${SCRIPT_DIR}/gitconfig ${HOME}/.gitconfig
ln -sf ${SCRIPT_DIR}/inputrc ${HOME}/.inputrc
ln -sf ${SCRIPT_DIR}/kitty ${HOME}/.config/kitty
ln -sf ${SCRIPT_DIR}/neovim-conf ${HOME}/.config/nvim
ln -sf ${SCRIPT_DIR}/profile ${HOME}/.profile
ln -sf ${SCRIPT_DIR}/ruby-version ${HOME}/.ruby-version
ln -sf ${SCRIPT_DIR}/starship.toml ${HOME}/.config/starship.toml
ln -sf ${SCRIPT_DIR}/tmux ${HOME}/.tmux
ln -sf ${SCRIPT_DIR}/tmux.conf ${HOME}/.tmux.conf
ln -sf ${SCRIPT_DIR}/zprofile ${HOME}/.zprofile
ln -sf ${SCRIPT_DIR}/zshaliases ${HOME}/.oh-my-zsh/custom/aliases.zsh
ln -sf ${SCRIPT_DIR}/zshenv ${HOME}/.zshenv
ln -sf ${SCRIPT_DIR}/zshrc ${HOME}/.zshrc
